name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Enable corepack
        run: corepack enable # Enables use of pnpm

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ">= 20.12.2"

      # Install dependencies
      - name: Install NPM Deps
        run: pnpm install

      - name: Test
        run: pnpm run test:ci

      - name: Build
        env:
          EXTENSION_VERSION: "v1.2.3"
        run: pnpm run build
