name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

      # Install dependencies
      - name: Install NPM Deps
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
