name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      # Install dependencies
      - name: Install NPM Deps
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
