name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      # Install dependencies
      - name: Install NPM Deps
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
