name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      # Install dependencies
      - name: Install NPM Deps
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
