name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Enable corepack
        run: corepack enable # Enables use of pnpm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">= 18.13.0"

      # Install dependencies
      - name: Install NPM Deps
        run: pnpm install

      - name: Lint
        run: pnpm run lint:check

      - name: Build
        run: pnpm run build
