name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Enable corepack
        run: corepack enable # Enables use of pnpm

      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: ">= 20.12.2"

      # Install dependencies
      - name: Install NPM Deps
        run: pnpm install

      - name: Test
        run: pnpm run test:ci

      - name: Build
        env:
          EXTENSION_VERSION: "v1.2.3"
        run: pnpm run build
