name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3

      # Install dependencies
      - name: Install NPM Deps
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
