name: Publish Extension

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Enable corepack
        run: corepack enable # Enables use of pnpm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">= 18.13.0"

      # Install dependencies
      - name: Install NPM Deps
        run: pnpm install

      - name: Test
        run: pnpm run test:ci

      - name: Build
        env:
          EXTENSION_VERSION: ${{ github.ref_name }}
        run: pnpm run build

      - name: GitHub Tag Name
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Upload zip to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload $GITHUB_REF_NAME ./gauntface-pin-it-extension.zip

      - name: Upload sourcemaps to Sentry
        run: ./sentry-upload.js

      - name: Upload extension to Chrome Web Store
        env:
          EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        run: |
          pnpm run chrome-webstore-upload -- upload \
            --auto-publish \
            --source gauntface-pin-it-extension.zip \
            --extension-id $EXTENSION_ID \
            --client-id $CLIENT_ID \
            --client-secret $CLIENT_SECRET \
            --refresh-token $REFRESH_TOKEN
