name: Publish Extension

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version, i.e. 0.2.1"
        required: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Set Extension Version
        shell: bash
        run: echo EXTENSION_VERSION="${{ inputs.version }}" >> $GITHUB_ENV

      # Get the code
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Enable corepack
        run: corepack enable # Enables use of pnpm

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: ">= 20.12.2"

      # Install dependencies
      - name: Install NPM Deps
        run: pnpm install

      - name: Test
        run: pnpm run test:ci

      - name: Build
        env:
          EXTENSION_VERSION: ${{ env.EXTENSION_VERSION }}
        run: pnpm run build

      - name: GitHub Tag Name
        env:
          EXTENSION_VERSION: ${{ env.EXTENSION_VERSION }}
        run: |
          echo "EXTENSION_VERSION: $EXTENSION_VERSION"

      - name: Create GitHub release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        id: create_release
        with:
          generateReleaseNotes: true
          artifacts: gauntface-pin-it-extension.zip
          artifactContentType: application/zip
          makeLatest: true
          name: "v${{ env.EXTENSION_VERSION }}"
          tag: "${{ env.EXTENSION_VERSION }}"

      - name: Upload sourcemaps to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: ./sentry-upload.js

      - name: Upload extension to Chrome Web Store
        env:
          EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        run: |
          pnpm run chrome-webstore-upload upload \
            --auto-publish \
            --source gauntface-pin-it-extension.zip \
            --extension-id $EXTENSION_ID \
            --client-id $CLIENT_ID \
            --client-secret $CLIENT_SECRET \
            --refresh-token $REFRESH_TOKEN
