name: Publish Extension

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      # Get the code
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Enable corepack
        run: corepack enable # Enables use of pnpm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">= 18.13.0"

      # Install dependencies
      - name: Install NPM Deps
        run: pnpm install

      - name: Test
        run: pnpm run test:ci

      - name: Build
        run: pnpm run build

      - name: GitHub Tag Name
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
